# -*- coding: utf-8 -*-
"""assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BvmSAgTb7UsxRq_FzNqwx3E2gLi-AJZO
"""

!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
downloaded = drive.CreateFile({'id':'1xVOo2nc-12aVSRH3z-5ZLF96qbVZMFCf'})
downloaded.GetContentFile('resources.csv')
import pandas as pd
xyz = pd.read_csv('resources.csv') 
print(xyz.head())